// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// cmEst_cpp
Rcpp::List cmEst_cpp(StringVector string_formula1, StringVector string_formula2, DataFrame data);
RcppExport SEXP _iRegression_cmEst_cpp(SEXP string_formula1SEXP, SEXP string_formula2SEXP, SEXP dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< StringVector >::type string_formula1(string_formula1SEXP);
    Rcpp::traits::input_parameter< StringVector >::type string_formula2(string_formula2SEXP);
    Rcpp::traits::input_parameter< DataFrame >::type data(dataSEXP);
    rcpp_result_gen = Rcpp::wrap(cmEst_cpp(string_formula1, string_formula2, data));
    return rcpp_result_gen;
END_RCPP
}
// modmEst_cpp
List modmEst_cpp(arma::vec xmin, arma::vec xup, arma::vec ymin, arma::vec yup);
RcppExport SEXP _iRegression_modmEst_cpp(SEXP xminSEXP, SEXP xupSEXP, SEXP yminSEXP, SEXP yupSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type xmin(xminSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type xup(xupSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type ymin(yminSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type yup(yupSEXP);
    rcpp_result_gen = Rcpp::wrap(modmEst_cpp(xmin, xup, ymin, yup));
    return rcpp_result_gen;
END_RCPP
}

RcppExport SEXP _iRegression_modm(SEXP, SEXP, SEXP, SEXP);

static const R_CallMethodDef CallEntries[] = {
    {"_iRegression_cmEst_cpp", (DL_FUNC) &_iRegression_cmEst_cpp, 3},
    {"_iRegression_modmEst_cpp", (DL_FUNC) &_iRegression_modmEst_cpp, 4},
    {"_iRegression_modm",      (DL_FUNC) &_iRegression_modm,      4},
    {NULL, NULL, 0}
};

RcppExport void R_init_iRegression(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
