// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// modm2
List modm2(arma::vec xmin, arma::vec xup, arma::vec ymin, arma::vec yup);
RcppExport SEXP _iRegression_modm2(SEXP xminSEXP, SEXP xupSEXP, SEXP yminSEXP, SEXP yupSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type xmin(xminSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type xup(xupSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type ymin(yminSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type yup(yupSEXP);
    rcpp_result_gen = Rcpp::wrap(modm2(xmin, xup, ymin, yup));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_iRegression_modm2", (DL_FUNC) &_iRegression_modm2, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_iRegression(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
