# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cmEst_cpp <- function(x1, x2, y1, y2) {
    .Call(`_iRegression_cmEst_cpp`, x1, x2, y1, y2)
}

modm2 <- function(xmin, xup, ymin, yup) {
    .Call(`_iRegression_modm2`, xmin, xup, ymin, yup)
}

