# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cmEst_cpp <- function(string_formula1, string_formula2, data) {
    .Call(`_iRegression_cmEst_cpp`, string_formula1, string_formula2, data)
}

modmEst_cpp <- function(variables1, variables2, data) {
    .Call(`_iRegression_modmEst_cpp`, variables1, variables2, data)
}

