# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

modm2 <- function(xmin, xup, ymin, yup) {
    .Call('_iRegression_modm2', PACKAGE = 'iRegression', xmin, xup, ymin, yup)
}

